version: '3.9'

services:
  front:
    build:
      dockerfile: Dockerfile-front
      context: .

  postgres:
    container_name: postgres
    image: postgres:14.8
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    depends_on:
      - front
    ports:
      - "54321:5432"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: star_burger:latest
    container_name: star_burger
    depends_on:
      - postgres
    volumes:
      - static_volume:/star-burger/static
      - media_volume:/star-burger/media
    env_file:
      - .env
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always

  nginx:
    container_name: star_burger_nginx
    image: nginx:1.18.0
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/star-burger/static
      - media_volume:/star-burger/media
    depends_on:
      - django
    ports:
      - "80:80"
    restart: always

volumes:
  static_volume:
  media_volume:
