# Generated by Django 3.2.15 on 2023-05-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0003_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('cooking', 'Готовится'), ('on_the_way', 'В пути'), ('delivered', 'Доставлен')], default='new', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
