# Generated by Django 3.2.15 on 2023-05-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Готовится', 'Готовится'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен')], default='new', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
