# Generated by Django 3.2.15 on 2023-05-29 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0008_order_way_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.restaurant'),
        ),
    ]
