# Generated by Django 3.2.15 on 2023-05-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0010_auto_20230530_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lon',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Долгота'),
        ),
    ]
