# Generated by Django 3.2.15 on 2023-07-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0011_auto_20230530_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Комментарий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Готовится', 'Готовится'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен')], default='Новый', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
