# Generated by Django 3.2.15 on 2023-07-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0012_auto_20230701_0602'),
        ('foodcartapp', '0012_auto_20230703_0155'),
    ]

    operations = [
    ]
